language: node_js
node_js:
  - "6"
install:
  - npm install
script:
  - npm run-script tslint

jobs:
  include:
    - stage: deploy to github pages
      if: branch = master
      script: 'npm run-script deploy'